### ISSUE TITLE
Rancher Machine-Driver error when inserting credentials: "Forbidden: Incorrect Username or Password"

### ISSUE THREAD

**Issue by CayoM** [profitbricks/ui-driver-profitbricks#5]
Versions:
CentOS7
Rancher-Server: docker.io/rancher/server:latest
Profitbricks UI Provider: https://profitbricks.github.io/ui-driver-profitbricks/docs/1.2.0/component.js

Issue:
When deploying a fresh rancher-server im unable to insert a host via Machine-Driver since the Profitbricks Plugin (v1.3.3 - https://profitbricks.github.io/ui-driver-profitbricks/docs/1.2.0/component.js) is not working. I cant use the credentials, because whatever im using it prints me the error:

Forbidden: Incorrect Username or Password

Unfortunately im not able to debug further, because nothing related is beeing logged at all.

The credentials are working in the profitbricks website tho. 

Steps to reproduce:
- run "docker run -d --restart=unless-stopped -p 8080:8080 rancher/server" on any server with docker 1.12.6 installed
- to do Admin -> Machine Drivers
- activate and update Profitbricks driver
- add new host -> select Profitbricks machine driver
- insert credentials
--> Error: Forbidden: Incorrect Username or Password

**Comment by alibazlamit** [comment]
Sorry for the inconvenience
If you could please navigate to http://<RANCHER SERVER ADDRESS>:8080/admin/settings and expand the Advanced Settings at the bottom of the page, you will find a value called `api.proxy.whitelist` you might need to add `,api.profitbricks.com` at the end of the string value.

This is supposed to be automatically added but we will look into the issue and see why it has not been, meanwhile you can just add the value manually so you can use the UI.

Regards

**Comment by CayoM** [comment]
Thank you so much for the help @alibazlamit !!!

Now i could connect to the api!

Unfortunately im not able to use the proposed images:

Error with pre-create check: "The image/alias ubuntu:16.04 de/fkb does not exist."
Error with pre-create check: "The image/alias ubuntu:14.04 de/fkb does not exist."

should i create a new issue for this?

**Comment by alibazlamit** [comment]
Did you create/choose a Datacenter with location de/fkb? if you can provide the steps you took to create the node please.

Thanks

**Comment by alibazlamit** [comment]
Another question that might help figure out the cause, which release are you using from [these] as the drivers machine (https://github.com/profitbricks/docker-machine-driver-profitbricks/releases), i believe it is recommended to use the `v1.3.3` release.

**Comment by CayoM** [comment]
the Steps i took was:

- insert credentials
- choose one of our datacenters (all of them are in de/fkb)
- continue to node configuration
- choose one of the selectable images (the Ubuntu images are not working. With the selectable Debian8 i would provision a new machine. So only the both Ubuntus are not working)


This is the standard driver from the profitbricks plugin (i didnt change anything):
https://github.com/profitbricks/docker-machine-driver-profitbricks/releases/download/v1.3.3/docker-machine-driver-profitbricks-v1.3.3-linux-amd64.tar.gz

**Comment by CayoM** [comment]
another thing i just realized:

using the default debian8 image to provision a rancher/kubernetes node is not optimal, since the node wont come up properly in kubernetes.

The issue is addressed here https://github.com/kubernetes-incubator/kubespray/issues/1227

I guess the bootstrap script would have to be changed with the mentioned changes in the issue above in order to make it work.

**Comment by alibazlamit** [comment]
Could you please run this `https://api.profitbricks.com/cloudapi/v4/locations/de/fkb` at your browser or using CURL, and post me back the JSON response. I just want to eliminate the possibility of an image alias issue

**Comment by CayoM** [comment]
Sure, here the output:

{
  "id" : "de/fkb",
  "type" : "location",
  "href" : "https://api.profitbricks.com/cloudapi/v4/locations/de/fkb",
  "properties" : {
    "name" : "karlsruhe",
    "features" : [ "SSD", "MULTIPLE_CPU" ],
    "imageAliases" : [ "centos:6_iso", "opensuse:latest", "opensuse:42.3_iso", "windows:latest", "debian:8_iso", "centos:7", "centos:7_iso", "clonezilla:latest_iso", "fedora:25_iso", "grml:latest_iso", "opensuse:13.2_iso", "debian:9", "debian:latest", "opensuse:42.2_iso", "fedora:25", "fedora:latest", "ubuntu:14.04_iso", "windows:2008r2", "ubuntu:17.04_iso", "zenloadbalancer:latest_iso", "mssql:2012_trial_iso", "windows:virtiodriver_iso", "windows:2008r2_iso", "windows:2012r2_iso", "windows:2013_recovery_iso", "windows:2016_iso", "windows:2012r2", "windows:2016", "gparted:latest_iso", "clearos:latest_iso", "ubuntu:16.04_iso", "debian:9_iso", "centos:6", "fedora:26_iso", "centos:latest", "debian:7", "debian:8", "debian:testing", "ubuntu:14.04", "ubuntu:16.04", "ubuntu:latest", "opensuse:13.2" ]
  }
}

**Comment by alibazlamit** [comment]
I have tried to reproduce the issue with both a local and a hosted instance, i was not able reproduce the issue.

You can try two things:

- Swtich back to version 1.2.3 and try using it.

- From the Admin section you can delete/deactivate the existing profitbricks driver, create a new driver using `https://github.com/profitbricks/docker-machine-driver-profitbricks/releases/download/v1.3.3/docker-machine-driver-profitbricks-v1.3.3-linux-amd64.tar.gz` as the download URL and `https://profitbricks.github.io/ui-driver-profitbricks/docs/1.2.0/component.js` as the custom UI url.

**Comment by CayoM** [comment]
the old version worked fine, but unfortunately had not the option to select datacenter, thats why it was not usable for us.

trying your second solution have worked. After deleting the driver and inserting it manually enabled me to select the ubuntu 16.04 image.

thanks for your help!
